/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import scala.util.Properties

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {

    println()
    println("----------------------------------------------")
    println("Java version: " + System.getProperty("java.version"));
    println("Kotlin version: ${KotlinVersion.CURRENT}")
    println("Scala version: ${Properties.versionString()}")
    println("----------------------------------------------")
    println()

    println(App().greeting)
    println(Library().someLibraryMethod())
    Spike1().go()
}

